### ISSUE TITLE
partial commit desn't work with -o

### ISSUE THREAD

**Issue by chmike** [sdg-mit/gitless#114]
I'm using gitless version 0.8.4. I could not select sections of modifications to commit with the option -p or --partial as advertised when specifying a particular file to commit with -o. I didn't explore further under what condition it would work.

**Comment by spderosso** [comment]
I've been unable to reproduce the bug. If you run into this problem again, please reopen the issue with more info (like the output from `gl status`)

**Comment by chmike** [comment]
I don't have the rights to reopen the issue. 

I tried on a blank project ad it worked. 
However, if I select q, immediately, the commit I'm asked for the commit message. Shouldn't the commit be aborted ?
Also, if I type n (no)  to not accept any change, I'm also asked for the commit message and the commit succeeds. 
Checking with gitk, a commit is performed in both cases but it contains no code change. The commit should be canceled if no code change is validated. 

I don't know why the -p doesn't work for the other project, It has many changes to the code. Here I just tested a simple hello world repo with a single line change.

**Comment by chmike** [comment]
I tried again to use commit -p in my main program without success. Here is the output:

```
$ gl status
On branch refactor-fileToSend, repo-directory //core

Tracked files with modifications:
  ➜ these will be automatically considered for commit
  ➜ use gl untrack f if you don't want to track changes to file f
  ➜ if file f was committed before, use gl checkout f to discard local changes

    message.go
    message_test.go
    ../file/file.go
    ../file/file_test.go


Untracked files:
  ➜ these won't be considered for commit
  ➜ use gl track f if you want to track changes to file f

    There are no untracked files to list
$ gl commit -o message.go message_test.go -m "rename MsgAck to AckMsg" -p
No changes.
No changes.
✔ Commit succeeded

Commit Id: ba3e73d200663b8488ba688c555bfd9a985363a1
. . . 
```
