### ISSUE TITLE
Better documentation on how to start a new branch off another branch

### ISSUE THREAD

**Issue by lehoff** [sdg-mit/gitless#117]
This could be down to me not being able to find the this in the manual, but here is my problem...

By experiment I have found out that I can do:
```
gl branch -c new-branch -dp origin/some-branch
gl switch new-branch
gl branch -su origin/some-branch
```
And then we are in business!

If this is already in the documentation please direct me to it.
If not, please tell me how I can submit PRs on the gitless.com documentation.

My first attempt at fixing a branch went through `git show-ref branch-name` to get the commit hasd and then do a `gl branch -sh commit`. Not a pleasant experience...

**Comment by chmike** [comment]
I'm not sure that `-dp origin/some-branch` is correct. 
The documentation is available at gitless.com.

What do you want to do ? If you simply want to start a branch rooted at HEAD of the current branch, with remote tracking on origin, all you need to do is 

    gl branch -c new-branch
    gl switch new-branch
    gl branch -su origin/some-branch

The later fails because the remote branch doesn't exist.
The weird thing is that if I try to switch back to my previous branch I get an error 
```
gl branch -su origin/test
✘ Branch "test" doesn't exist in remote "origin"
X meessen@marc ~/Sources/go/src/FileSync/core [test * >3] 
12:40 $ gl switch refactor-fileToSend
Traceback (most recent call last):
  File "gl.py", line 14, in <module>
  File "gitless/cli/gl.py", line 87, in main
  File "gitless/cli/pprint.py", line 80, in err
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 97: ordinal not in range(128)
Failed to execute script gl
```

If I try your first instruction I also get an error 
```
gl branch -c test2 -dp origin/test2
✘ Some internal error occurred
  ➜ If you want to help, see http://gitless.com for info on how to report bugs and include the following information:
  
  0.8.4
  
  Traceback (most recent call last):
    File "gitless/cli/gl.py", line 73, in main
    File "gitless/cli/gl_branch.py", line 60, in main
    File "gitless/cli/gl_branch.py", line 105, in _do_create
    File "gitless/core.py", line 118, in revparse_single
  AttributeError: 'NoneType' object has no attribute 'head'
```
I don't think that Python is the right language to program gitless.

**Comment by chmike** [comment]
The right way to do what you wanted is as following

```
$ gl branch -c test3 origin/test3
$ gl switch test3
$ gl branch -su origin/test3
```

You can create more than one branch with `gl branch -c`. So you create the local branch and the remote branch on origin. They may not have the same branch name.

**Comment by lehoff** [comment]
I was probably not clear enough in what I wanted to do.

I want to create a new branch off the tip of an existing branch on one of my remotes.
I know that the example I provided above works for suitable existing origin/some-branch.

My problem is that the documentation on gitless.com does not provide an example that shows that the divergent-point can be an existing remote branch.

For me this is a very common use case and I think it should be documented. I cannot see anything on divergent-point that explains that a branch name can be used as DP. Hence my offer to help out with the documentation.

**Comment by spderosso** [comment]
8b5384e90a7b641ff1a5153da13ba895e0669f35, 052852504648bac81fe138ae014eb4ea84543e91
