### ISSUE TITLE
Cherry Pick

### ISSUE THREAD

**Issue by cystbear** [sdg-mit/gitless#129]
Looks like `gl` stands for very beginner user of git Universe.
GL lacks very common feature like `cherry-pick` and so on.

Could you please develop one more git wrapper with name `g` and with only one command `make-happy`, usage will be quite simple `g make-happy`

**Comment by spderosso** [comment]
You can do the equivalent of `git rebase` or `git cherry-pick` with `gl fuse`. More info here: http://gitless.com/#gl-fuse
