### ISSUE TITLE
gl lists remote branches extremely slowly

### ISSUE THREAD

**Issue by OsePedro** [sdg-mit/gitless#137]
I have a repository with 10 remote branches. Over multiple runs of `time gl branch -r`, the average run time is 30 seconds. In contrast, `time git branch -r` runs in 2 milliseconds on average. The run time discrepancy is similar on other repositories with multiple branches. 
What does `gl branch -r` do that makes it about 15000 times slower than `git branch -r`?

**Comment by spderosso** [comment]
It's fetching them one by one. We need to create a new method in `core` that gets all remote branch info at once with one `git fetch`. Adding a `lookup_branches(self, branch_names)` that fetches all branches at once should make `gl branch -r` run fast like `git branch -r`

Relevant files:
https://github.com/sdg-mit/gitless/blob/master/gitless/cli/gl_branch.py#L111
https://github.com/sdg-mit/gitless/blob/master/gitless/core.py#L472-L489

Thanks for reporting this!
