### ISSUE TITLE
switch does not honor .gitignore

### ISSUE THREAD

**Issue by andrewsawczyn** [sdg-mit/gitless#147]
When switching branches, gitless does not honor .gitignore and will stash ignored files and directories.  This is true of the .gitignore file itself.   Each branch will have it's own version of .gitignore.   Is this a 'feature' or an issue?   Should ignored entries not be ignored?   This seems counterintuitive.

**Comment by andrewsawczyn** [comment]
I was able to fix this on my own by changing line 328 of core.py from '--all' to '--include-untracked' which seems like more logical behavior to me.

"If the --include-untracked option is used, all untracked files are also stashed and then cleaned up with git clean, leaving the working directory in a very clean state. If the --all option is used instead then the ignored files are stashed and cleaned in addition to the untracked files."

**Comment by spderosso** [comment]
The default behavior is to keep branches independent from each other so ignored files are stashed when you switch. If you'd like the changes in the current branch to follow you to the destination branch you can use the `-mo/--move-over` flag of `gl switch`

**Comment by andrewsawczyn** [comment]
I don't see the --move-over option as a suitable solution.  Ignored files should exist outside of git and should be ignored.   Having to use --move-over eliminates much of the benefit of gitless.

**Comment by spderosso** [comment]
Can you tell me more about your use case? What kind of files are you ignoring and why do you want them to follow you as you switch branches?

**Comment by andrewsawczyn** [comment]
I tend to keep notes and config files that are only of interest to me in my directories and I list these in .gitignore.  My big issue with gitless in switching branches is that it also stashes .gitignore. Which seems counter intuitive as it's a git control file.  I guess I could duplicate .gitignore per branch but that isn't a great solution.  It's a simple change (replacing --all with --include-untracked) and thanks to git/gitless I can maintain my own local branch of gitless so it's not a big deal.   

Other than this issue, gitless has solved 90% of my frustration in using git.
