### ISSUE TITLE
Is there a roadmap for gitless?

### ISSUE THREAD

**Issue by felix91gr** [sdg-mit/gitless#155]
I don't like `git`. It's confusing and messy. In fact, right now we're having chaos in another project just because of how `git` handles line endings...

That's why I like `gitless`. It's... easier to think about my repos with it. It's just better in most ways.
Hence, I want to know:

- Is its design still evolving? Do you have a mailing list for that?
- Are you still doing studies on the ergonomics of `git` and `gitless`, like [this one](https://spderosso.github.io/oopsla16.pdf)?

And... lemme know if there's parts where I can give effective feedback. VCS doesn't have to be as hard as it is today :)

**Comment by spderosso** [comment]
> I don't like git. It's confusing and messy. In fact, right now we're having chaos in another project just because of how git handles line endings...
> 

That's interesting, if you'd like to share what happened and what potential solutions (if any) you have in mind we can see if it is something that we can fix in Gitless

> That's why I like gitless. It's... easier to think about my repos with it. It's just better in most ways.
> Hence, I want to know:
> 
> Is its design still evolving? Do you have a mailing list for that?
> Are you still doing studies on the ergonomics of git and gitless, like this one?

There's no mailing list. I still have a few ideas I'd like to pursue but no specific roadmap yet. My top priority right now is to fix the bugs people have reported, but I am a swamped with other projects at the moment so it's hard for me to find the time to work on Gitless.

> And... lemme know if there's parts where I can give effective feedback. VCS doesn't have to be as hard as it is today :)

I agree! and feedback is always welcome. If you have some ideas you'd like to discuss feel free to open a new issue.

**Comment by techtonik** [comment]
I think that's a worthy goal for the starters - https://github.com/sdg-mit/gitless/issues/176
