### ISSUE TITLE
Incorrect messages when tracking files named with non-ASCII characters

### ISSUE THREAD

**Issue by ygohko** [sdg-mit/gitless#172]
When trying to track files that named with non-ASCII characters, Gitless outputs incorrect messages.

    $ gl track 日本語.txt 
    ✘ 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

    $ gl status
    On branch master, repo-directory //
    
    Tracked files with modifications:
      ➜ these will be automatically considered for commit
      ➜ use gl untrack f if you don't want to track changes to file f
      ➜ if file f was committed before, use gl checkout f to discard local changes
    
    /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gitless/cli/gl_status.py:98: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
      if fp == '.':
        日本語.txt (new file)
    
    
    Untracked files:
      ➜ these won't be considered for commit
      ➜ use gl track f if you want to track changes to file f
    
        There are no untracked files to list

Commit is looks like worked, but gl history -v does not work. 

    $ gl commit -m "Added a file named in Japanese."
    ✔ Commit on branch master succeeded
    
    Commit Id: fe3caf0b86f78a9d47c07ea5b9fc8b2c18438983
    Author:    XXXX XXXX <XXXX@XXXX>
    Date:      Wed Apr 25 17:53:22 2018 +0900
    
        Added a file named in Japanese.
    $ gl history -v
    ✘ 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

My environment: macOS 10.13.4, Python 2.7.14, Gitless 0.8.6

**Comment by ygohko** [comment]
I am investigating about the issue.
There are many implicit conversion from str to unicode. I think realistic solution would be adding sys.setdefaultencoding('utf-8') to user's site-packages/sitecustomize.py.
Now it works fine in my environment.

**Comment by techtonik** [comment]
Because `gitless` ships as a end-user app, maybe it should abandon Python 2.7?
