### ISSUE TITLE
Auto-upload --edge snap on every commit

### ISSUE THREAD

**Issue by techtonik** [sdg-mit/gitless#177]
@spderosso I sent you an invite to collaborate on managing `gitless` snap, so that you can setup automatic builds to `--edge` channel as described here https://tutorials.ubuntu.com/tutorial/continuous-snap-delivery-from-travis-ci#4

`snapcraft,yml` also needs more love to strip down resulting file system to just needed files. https://docs.snapcraft.io/build-snaps/advanced-features#finishing-steps I am not proficient enough in Linux compilation, but it seems to me that Perl and manual files should not be packed.

https://build.snapcraft.io/ can be an alternative for Travis builds, but I didn't look into it.

**Comment by spderosso** [comment]
@techtonik Thank you for the link with instructions. I believe it [worked](https://travis-ci.org/sdg-mit/gitless) (5f5ae31)?

**Comment by techtonik** [comment]
Yes. It works now:
```
$ sudo snap install gitless --edge --devmode
gitless (edge) 0+git.4eb3a97 from anatoly techtonik (techtonik) installed
```
Although I would like to pass the publishing rights to @sdg-mit.
