### ISSUE TITLE
Add HTTPS to the website

### ISSUE THREAD

**Issue by techtonik** [sdg-mit/gitless#184]
http://gitless.com/ is not secure and httpS://gitless.com/ has invalid certificate.

I would rather use secure website for snap description. From https://snapcraft.io/gitless/listing

![screen](https://user-images.githubusercontent.com/515889/46012127-ddb29900-c0d0-11e8-80e0-3157bfed710f.png)

Instructions are here https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by spderosso** [comment]
Thank you for the link. I updated the DNS records to enable https. I'll check back in ~24 hs to see if its working.

**Comment by techtonik** [comment]
https://gitless.com/ works already, but http://gitless.com/ is not redirected.

**Comment by spderosso** [comment]
done. It seems to be working now
