### ISSUE TITLE
How to undo a commit?

### ISSUE THREAD

**Issue by elviejo79** [sdg-mit/gitless#210]
I've just made a commit but I have changed my mind and actually want to undo that commit.

How can I do it?

**Comment by spderosso** [comment]
`gl branch -sh HEAD~` will reset your head to the commit before the last one (`HEAD~` is a shorthand for `HEAD~1`). It won't change the working directory, so your changes will still be there. After running that command you'll be in the same situation you were before you did the commit.

**Comment by elviejo79** [comment]
thank you!
