### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'remote_name'

### ISSUE THREAD

**Issue by cougarhawk** [sdg-mit/gitless#211]
After cloning our repository in a new location, and successfully running the "gl remote -c" command to point to the remote repository, I am unable to view a history of any branch in the remote repository nor am I able to fuse to it. I see the error message below:

> gl history -l 10 -c -b origin/master
✘ Some internal error occurred
  ➜ If you want to help, see http://gitless.com for info on how to report bugs and include the following information:
  
  0.8.8
  
  Traceback (most recent call last):
    File "/usr/lib/python3.6/site-packages/gitless/cli/gl.py", line 99, in main
      return SUCCESS if args.func(args, repo) else ERRORS_FOUND
    File "/usr/lib/python3.6/site-packages/gitless/cli/gl_history.py", line 36, in main
      b = helpers.get_branch(args.b, repo) if args.b else repo.current_branch
    File "/usr/lib/python3.6/site-packages/gitless/cli/helpers.py", line 23, in get_branch
      return _get_ref("branch", branch_name, repo)
    File "/usr/lib/python3.6/site-packages/gitless/cli/helpers.py", line 47, in _get_ref
      r = getattr(remote_repo, "lookup_" + ref_type)(remote_ref)
    File "/usr/lib/python3.6/site-packages/gitless/core.py", line 499, in lookup_branch
      return RemoteBranch(git_branch, self.gl_repo)
    File "/usr/lib/python3.6/site-packages/gitless/core.py", line 586, in __init__
      self.remote_name = self.git_branch.remote_name
  AttributeError: 'NoneType' object has no attribute 'remote_name'
 ----
Output of pip upgrade of gitless from 0.8.6 to 0.8.8:
Installing collected packages: pygit2, gitless
  Found existing installation: pygit2 0.26.4
    Uninstalling pygit2-0.26.4:
      Successfully uninstalled pygit2-0.26.4
  Found existing installation: gitless 0.8.6
    Uninstalling gitless-0.8.6:
      Successfully uninstalled gitless-0.8.6
Successfully installed gitless-0.8.8 pygit2-0.28.2
 ----
Machine information:
> uname -a
Linux XXXXXXX 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
----
OS Information:
> cat /etc/*release
CentOS Linux release 7.4.1708 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core) 
CentOS Linux release 7.4.1708 (Core) 
----
Do you have any ideas what caused this error or how to resolve it?

**Comment by cougarhawk** [comment]
To reproduce the issue consistently, I run the following steps from the UNIX console pointing to an empty directory:
$ gl init
$ gl remote -c origin git@github.privateserver:REPO/ae
$ gl history -l 10 -c -b origin/development

**Comment by spderosso** [comment]
Thank you for reporting this. Unfortunately, I am having trouble reproducing the error. I followed your steps using the gitless repo as origin (both https and ssh) and it works for me. Either it shows the history, or it shows an error message that the branch doesn't exist. I am running MacOS 10.14.5 with `git` v2.18.0.

From the stracktrace you've attached, it seems that the problem is in [`Remote.lookup_branch`](https://github.com/sdg-mit/gitless/blob/master/gitless/core.py#L492), where the call to [gite_repo.lookup_branch](https://github.com/sdg-mit/gitless/blob/master/gitless/core.py#L497) is returning `None`. This is not expected to happen because there's a [check above ](https://github.com/sdg-mit/gitless/blob/master/gitless/core.py#L493)to verify that the branch exists.

- What `git` version do you have installed? (run `git --version`)
- Do you expect `origin/development` to exist or not?

**Comment by cougarhawk** [comment]
I understand your confusion as I had come to the same conclusion based on my limited understanding of the core.py file. The remote branch "origin/development" does indeed exist and is accessible from a Windows installation of Gitless. The problems began to occur on my Linux development environment after our Github server was moved to a different location. 

My development environment consists of the following machines:
1) Windows 7 Enterprise: 
$ gl --version
GL Version: 0.8.5
You can check if there's a new version of Gitless available at http://gitless.com

$ git --version
git version 2.12.0.windows.1
*******
Gitless was installed when the repository was in the previous location. The steps to reproduce above do NOT result in an error when executed against the repository at the new location. This continues to work fine and as expected. 
*******

2) CentOS Linux release 7.4.1708 (Core): 
$ gl --version
GL Version: 0.8.8
You can check if there's a new version of Gitless available at http://gitless.com

$ git --version
git version 1.8.3.1
*******
Gitless v. 0.8.5 was installed when the repository was in the previous location. The steps to reproduce above did NOT result in an error when initially executed against the repository at the *old* location. The errors began occurring after the repository was moved to the new location. I upgraded Gitless on this machine to 0.8.6 then to 0.8.8 but the error persists on all versions. 
*******

3) Red Hat Enterprise Linux Server release 7.6 (Maipo):
$ gl --version
GL Version: 0.8.5
You can check if there's a new version of Gitless available at http://gitless.com

$ git --version
git version 1.8.3.1
*******
Gitless v. 0.8.5 was installed after the repository was moved to the new location and the previous Linux environment was not working as expected. I reproduced the same error on this machine as well.
*******

Update: I found a workaround to the issue so that allows me to move forward with development on my Linux environments.
$ gl init git@github.privateserver:REPO/ae
$ gl remote -c origin git@github.privateserver:REPO/ae
$ gl history -l 10 -c -b origin/development

The side-effect of specifying the remote repository as part of "gl init" is that Gitless proceeds to download all the branches as branches in the local repository. The remote repository consists of many branches (on the order of 20 or 30). I wanted to be able to download a single branch of my choosing from the remote repository and download it as a branch of my choosing in my local repository. So now, after downloading everything, I have to obtain a listing of all branches in my local repository and manually delete each one. After creating a default local branch and switching to that branch then manually deleting all the local branches via "gl branch -d", I am able to access the branch in the remote repository:

$ gl history -l 10 -c -b origin/development
e5c5b7e ...
865b43e ...
3f510cb ...
6bff9e2 ....
2eaab70 ...
90e99b0 ...
ec25be4 ...
c4ddd9e ...
0cae1be ...
631d7a7 ...

I am also able to create a local branch that specifies a branch in the remote repository as a divergent point:

$ gl branch -c mydev -dp origin/development
✔ Created new branch mydev

$ gl history -l 10 -c -b mydev
e5c5b7e ...
865b43e ...
3f510cb ...
6bff9e2 ...
2eaab70 ...
90e99b0 ...
ec25be4 ...
c4ddd9e ...
0cae1be ...
631d7a7 ...

This is the only way I am able to move forward on both Linux developments.

**Comment by spderosso** [comment]
> after our Github server was moved to a different location.

Perhaps the fact that the repo was moved is important. Yet, according to [GitHub](https://help.github.com/en/articles/renaming-a-repository), all `git clone`, `git fetch`, or `git push` operations targeting the previous location will continue to function as if made on the new location.  So the `git fetch` on [line 496](https://github.com/sdg-mit/gitless/blob/master/gitless/core.py#L496) should have worked correctly. I've tried the following:
- create github repo
- `gl init`, `gl branch -c origin/dev`
- rename github repo
- `gl branch -b origin/dev`. Works fine.

And I also tried `gl history -b origin/some-other-branch` on a repo without `some-other-branch` already fetched. It worked fine as well. 
 

> Update: I found a workaround to the issue so that allows me to move forward with development on my Linux environments.

Ok, I created issue #212. We should probably have a way for users to limit the branches that get downloaded.

**Comment by cougarhawk** [comment]
If you have any troubleshooting tools or runtime debugging traces that can generate more verbose information about what Gitless is doing in my development environment under the covers, please provide me with instructions and I will be more than happy to try it. Thanks.

**Comment by spderosso** [comment]
If you [install gitless from source](https://github.com/sdg-mit/gitless/#installing-from-source) and instead of doing `./setup.py install` you do `./setup.py develop` you can modify the source code to add print statements and see what gets printed out when you run `gl history -b origin/branch-that-fails`.

The problem is in [`Remote.lookup_branch`](https://github.com/sdg-mit/gitless/blob/master/gitless/core.py#L492) so if you add a few print statements there that should give us more info to figure out what's going on. For example, you can verify that `self.git_remote.name` and `branch_name` have the values  you expect.

I've just noticed something interesting. In [`Remote.lookup_branch`](https://github.com/sdg-mit/gitless/blob/master/gitless/core.py#L492) we sometimes use `self.name` to get the remote name and other times `self.git_remote.name`. It might be nothing, but perhaps you can also print `self.name` to confirm that it holds the same value a `self.git_remote.name`. It could be the case that  the [`git.fetch` on line 496](https://github.com/sdg-mit/gitless/blob/master/gitless/core.py#L496) has an effect on the remote.

what an interesting bug! I wish I could help you but I am having hard time reproducing it locally :/

**Comment by cougarhawk** [comment]
I modified the code at core.py to place several print statements:

```
  def lookup_branch(self, branch_name):
    if not stdout(git('ls-remote', '--heads', self.name, branch_name)):
      return None
    print 'DEBUG: PREFETCH: SELF.NAME: {0} - BRANCH: {1} - SELF.GIT_REMOTE_NAME: {2}\n'.format(self.name, branch_name, self.git_remote.name)
    # The branch exists in the remote
    git.fetch(self.git_remote.name, branch_name)
    print 'DEBUG: POSTFETCH: SELF.NAME: {0} - BRANCH: {1} - SELF.GIT_REMOTE_NAME: {2}\n'.format(self.name, branch_name, self.git_remote.name)
    print 'DEBUG: LOOKUP: BRANCH: {0}/{1} \n'.format(self.git_remote.name, branch_name)
    git_branch = self.gl_repo.git_repo.lookup_branch(
        self.git_remote.name + '/' + branch_name, pygit2.GIT_BRANCH_REMOTE)
    print 'DEBUG: PRE-REMOTEBRANCH: SELF.NAME: {0} - BRANCH: {1} - SELF.GIT_REMOTE_NAME: {2} - GITBRANCH: {3}\n'.format(self.name, branch_name, self.git_remote.name, git_branch)
    return RemoteBranch(git_branch, self.gl_repo)

```

DEBUG: PREFETCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin

DEBUG: POSTFETCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin

DEBUG: LOOKUP: BRANCH: origin/development 

DEBUG: PREFETCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin - GITBRANCH: None

✘ Some internal error occurred
  ➜ If you want to help, see http://gitless.com for info on how to report bugs and include the following information:
  
  0.8.8
  
  Traceback (most recent call last):
    File "build/bdist.linux-x86_64/egg/gitless/cli/gl.py", line 99, in main
      return SUCCESS if args.func(args, repo) else ERRORS_FOUND
    File "build/bdist.linux-x86_64/egg/gitless/cli/gl_history.py", line 36, in main
      b = helpers.get_branch(args.b, repo) if args.b else repo.current_branch
    File "build/bdist.linux-x86_64/egg/gitless/cli/helpers.py", line 23, in get_branch
      return _get_ref("branch", branch_name, repo)
    File "build/bdist.linux-x86_64/egg/gitless/cli/helpers.py", line 47, in _get_ref
      r = getattr(remote_repo, "lookup_" + ref_type)(remote_ref)
    File "build/bdist.linux-x86_64/egg/gitless/core.py", line 503, in lookup_branch
      return RemoteBranch(git_branch, self.gl_repo)
    File "build/bdist.linux-x86_64/egg/gitless/core.py", line 590, in __init__
      self.remote_name = self.git_branch.remote_name
  AttributeError: 'NoneType' object has no attribute 'remote_name'
**************
So the strings are coming in ok yet the call to self.gl_repo.git_repo.lookup_branch returns an empty branch. If you have the opportunity to create a file with code changes over the gitless 0.8.8 source that I can overlay in my development environment that you wish me to try, let me know.

**Comment by cougarhawk** [comment]
When I initialize my directory by specifying the full github details and delete all the unwanted local branches, I see the following:

$ gl history -l 10 -c -b origin/development                 
DEBUG: PREFETCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin

DEBUG: POSTFETCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin

DEBUG: LOOKUP: BRANCH: origin/development 

DEBUG: PRE-REMOTEBRANCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin - GITBRANCH: <_pygit2.Branch object at 0x15873d0>

4ecb52c ...
c56ffb9 ...
5779114 ...
d8d0c96 ...
931e5d9 ...
fa78c17 ...
f4b8f1c ...
f0067b9 ...
b3e018c ...
fd401c2 ...

**Comment by spderosso** [comment]
Thanks. It looks like we are making the right call to pgyit2, with the correct arguments. They even have a [test case where they do a similar lookup_branch](https://github.com/libgit2/pygit2/blob/master/test/test_branch.py#L288). So why would pygit2/libgit2 say there's no `origin/development` branch? hmm...

Perhaps `git fetch` is failing silently and not fetching the branch for some reason. In the repo where you see the error,  run (in your shell) `git fetch origin development`. Do you notice something strange in the output?

**Comment by cougarhawk** [comment]
When I execute `git fetch origin development`, the following output displays almost immediately:

$ git fetch origin development_             
From github.gwd.broadcom.net:ESD/ae_
\* branch            development -> FETCH_HEAD_

However, nothing is ever actually fetched:
$ gl history -l 10 -c 
b9ed37d Initialize repository

**Comment by spderosso** [comment]
Weird, it's definitely not a gitless problem then. Now the question is why isn't `git fetch` fetching the branch. Perhaps [this SO question](https://stackoverflow.com/questions/11623862/git-fetch-doesnt-fetch-all-branches), helps?

If your `remote.origin.fetch` config looks OK then you can try removing and readding the remote and checking if `git fetch` then works. If it does, then it's a `git` bug. What we can do in Gitless is readd the remote if `git fetch` returns `None`.

**Comment by cougarhawk** [comment]
On the environment where the issue occurs, the git remote show command does output all branches from the origin:
********
$ git config --get remote.origin.fetch     
+refs/heads/\*:refs/remotes/origin/\*

$ git remote -v
origin  git@github.privateserver:REPO/ae (fetch)
origin  git@github.privateserver:REPO/ae (push)

$ git ls-remote --get-url origin    
git@github.privateserver:REPO/ae

$ git remote show origin                   
\* remote origin
  Fetch URL: git@github.privateserver:REPO/ae
  Push  URL: git@github.privateserver:REPO/ae
  HEAD branch: development
  Remote branches:
    BRANCH_1                    new (next fetch will store in remotes/origin)
    BRANCH_2                    new (next fetch will store in remotes/origin)
...
    BRANCH_30                    new (next fetch will store in remotes/origin)
    development                                     new (next fetch will store in remotes/origin)
    master                                          new (next fetch will store in remotes/origin)
  Local ref configured for 'git push':
    master pushes to master (local out of date)
**********
I experimented with removing and re-adding the repository. Here are my results:
**********
$ git remote rm origin

$ git remote -v

$ git remote show origin                              
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

$ gl remote
List of remotes:
  ➜ do gl remote -c r r_url to add a new remote r mapping to r_url
  ➜ do gl remote -d r to delete remote r

    There are no remotes to list

$ gl history -l 10 -c -b origin/development
✘ Remote "origin" doesn't exist, and there is no local Branch "origin/development"

$ git remote add origin git@github.privateserver:REPO/ae

$ gl remote
List of remotes:
  ➜ do gl remote -c r r_url to add a new remote r mapping to r_url
  ➜ do gl remote -d r to delete remote r

    origin (maps to git@github.privateserver:REPO/ae)

$ git remote -v                                           
origin  git@github.privateserver:REPO/ae (fetch)
origin  git@github.privateserver:REPO/ae (push)

$ gl history -l 10 -c -b origin/development
DEBUG: PREFETCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin

DEBUG: POSTFETCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin

DEBUG: LOOKUP: BRANCH: origin/development 

DEBUG: PRE-REMOTEBRANCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin - GITBRANCH: None

✘ Some internal error occurred
  ➜ If you want to help, see http://gitless.com for info on how to report bugs and include the following information:
  
  0.8.8
  
  Traceback (most recent call last):
    File "build/bdist.linux-x86_64/egg/gitless/cli/gl.py", line 99, in main
      return SUCCESS if args.func(args, repo) else ERRORS_FOUND
    File "build/bdist.linux-x86_64/egg/gitless/cli/gl_history.py", line 36, in main
      b = helpers.get_branch(args.b, repo) if args.b else repo.current_branch
    File "build/bdist.linux-x86_64/egg/gitless/cli/helpers.py", line 23, in get_branch
      return _get_ref("branch", branch_name, repo)
    File "build/bdist.linux-x86_64/egg/gitless/cli/helpers.py", line 47, in _get_ref
      r = getattr(remote_repo, "lookup_" + ref_type)(remote_ref)
    File "build/bdist.linux-x86_64/egg/gitless/core.py", line 503, in lookup_branch
      return RemoteBranch(git_branch, self.gl_repo)
    File "build/bdist.linux-x86_64/egg/gitless/core.py", line 590, in __init__
      self.remote_name = self.git_branch.remote_name
  AttributeError: 'NoneType' object has no attribute 'remote_name'

$ git remote show origin                   
\* remote origin
  Fetch URL: git@github.privateserver:REPO/ae
  Push  URL: git@github.privateserver:REPO/ae
  HEAD branch: development
  Remote branches:
    BRANCH_1                    new (next fetch will store in remotes/origin)
    BRANCH_2                    new (next fetch will store in remotes/origin)
...
    BRANCH_30                    new (next fetch will store in remotes/origin)
    development                                     new (next fetch will store in remotes/origin)
    master                                          new (next fetch will store in remotes/origin)
  Local ref configured for 'git push':
    master pushes to master (local out of date)
**********
If I manually execute "git fetch", I am able to fetch everything. Then Gitless works as before.

**********
$ git fetch
warning: no common commits
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 96970 (delta 2), reused 2 (delta 0), pack-reused 96953
Receiving objects: 100% (96970/96970), 207.11 MiB | 31.04 MiB/s, done.
Resolving deltas: 100% (62064/62064), done.
From git@github.privateserver:REPO/ae
 \* [new branch]      BRANCH_1 -> origin/BRANCH_1
 \* [new branch]      BRANCH_2 -> origin/BRANCH_2
...
 \* [new branch]      BRANCH_30 -> origin/BRANCH_30
 \* [new branch]      development -> origin/development
 \* [new branch]      master     -> origin/master

$ gl history -l 10 -c -b origin/development
DEBUG: PREFETCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin

DEBUG: POSTFETCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin

DEBUG: LOOKUP: BRANCH: origin/development 

DEBUG: PRE-REMOTEBRANCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin - GITBRANCH: <_pygit2.Branch object at 0x2cc2410>

ef86e54 ...
9f83db1 ...
2ef1ce8 ...
a04eef0 ...
94e7563 ...
a4d1a57 ...
bc5f10e ...
c29525a ...
23bdb40 ...
42baa4f ...

$ gl branch
List of branches:
  ➜ do gl branch -c b to create branch b
  ➜ do gl branch -d b to delete branch b
  ➜ do gl switch b to switch to branch b
  ➜ \* = current branch

    \* master 
**********

So it appears that the fetch operation as executed from Gitless is not behaving as expected in my environment. 

This experiment has given me a better workaround to this issue. The solution is just to manually execute "git fetch" in my local branch initialized by the command "gl init" (no URL) after adding the remote repository via the "gl remote -c".

**Comment by spderosso** [comment]
> So it appears that the fetch operation as executed from Gitless is not behaving as expected in my environment.

Gitless is running `git fetch origin development` and not `git fetch`. From your [previous comment](https://github.com/sdg-mit/gitless/issues/211#issuecomment-518224147), it seems that `git fetch origin development` doesn't work but `git fetch` does.  I can change the code so that we do a `git fetch` if we get `None` back from the `lookup_branch`.  That should fix the bug.

**Comment by cougarhawk** [comment]
I just ran a few tests locally and I have come to the conclusion that it will be better to execute the command `git fetch remote_repository` (no branch) rather than `git fetch` (no remote repository nor branch). This guarantees that you always fetch the requested remote repository in an environment where you have multiple remote repositories. I can reproduce the errors with `git fetch` if I specify a second remote repository.

As you observed, while the command `git fetch remote_repository branch` does download objects from the repository, the `lookup_branch` method as executed by Gitless in my environment returns `None`. I have verified that the call is always successful after you execute the command `git fetch remote_repository`.

But I think we have a plan of action to solve this issue. Thanks for the responses.

**Comment by spderosso** [comment]
Great, thanks for your help debugging. Since `git fetch remote_repository branch` works in most cases I am inclined to leave that as it is and only do `git fetch remote_repository` if `lookup_branch` returns `None`. That way we don't fetch all branches unless it's absolutely necessary.

If I understand correctly, the problem is in our call to `git fetch remote_repo branch`? From your [comment here](https://github.com/sdg-mit/gitless/issues/211#issuecomment-518224147), it seems that it didn't fetch anything (even when the branch *does* exist in the remote)? That would suggest that the bug is not in pygit2's `lookup_branch` but that our `git fetch remote_repo branch` call is not really fetching `branch` in your environment

Comparing the outputs of your calls to `git fetch origin development` and `git fetch` confirm this:

> $ git fetch origin development_
> From github.gwd.broadcom.net:ESD/ae_
> * branch development -> FETCH_HEAD_

> $ git fetch
> warning: no common commits
> remote: Enumerating objects: 17, done.
> remote: Counting objects: 100% (17/17), done.
> remote: Compressing objects: 100% (17/17), done.
> remote: Total 96970 (delta 2), reused 2 (delta 0), pack-reused 96953
> Receiving objects: 100% (96970/96970), 207.11 MiB | 31.04 MiB/s, done.
> Resolving deltas: 100% (62064/62064), done.
> From git@github.privateserver:REPO/ae
> * [new branch] BRANCH_1 -> origin/BRANCH_1
> * [new branch] BRANCH_2 -> origin/BRANCH_2
> ...
> * [new branch] BRANCH_30 -> origin/BRANCH_30
> * [new branch] development -> origin/development
> * [new branch] master -> origin/master


I wonder if we are executing the wrong command. The [git fetch docs](https://git-scm.com/docs/git-fetch) say the following about the `<refspec>` parameter (which is `development` in our case):

> Specifies which refs to fetch and which local refs to update.
> The format of a <refspec> parameter is an optional plus +, followed by the source <src>, followed by a colon :, followed by the destination ref <dst>. The colon can be omitted when <dst> is empty.
> The remote ref that matches <src> is fetched, and if <dst> is not an empty string, an attempt is made to update the local ref that matches it.

Unfortunately, it doesn't say what happens when `dst` is not specified. But I always assumed it was the same as saying `git fetch remote branch:branch`. And there are [docs](https://www.atlassian.com/git/tutorials/syncing/git-fetch) that say that running `git fetch repo branch` will fetch that remote branch.

**Comment by cougarhawk** [comment]
I agree with your approach to fetch the branch and fetching the remote repository only when the lookup_branch returns None. Fetching just the remote branch works on my Windows environment and it used to work at some point on my Linux environment before we moved the repository.

I mentioned in a previous comment that the command `git fetch repo branch` did not appear to fetch anything but I now believe that the branch was fetched over the course of the `gl history -b repo/branch` command.

The `git fetch repo branch` command can show nothing if there are no diffs from the remote branch to fetch since the previous time the remote branch was fetched:

**************
$ gl init
✔ Local repo created in /home/user/gltest

$ gl remote -c origin git@github.privateserver:REPO/ae
✔ Remote origin mapping to git@github.privateserver:REPO/ae created successfully
  ➜ to list existing remotes do gl remote
  ➜ to remove origin do gl remote -d origin

$ git fetch origin development                          
warning: no common commits
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 84081 (delta 20), reused 23 (delta 18), pack-reused 84041
Receiving objects: 100% (84081/84081), 203.54 MiB | 35.84 MiB/s, done.
Resolving deltas: 100% (53221/53221), done.
From github.privateserver:REPO/ae
 \* branch            development -> FETCH_HEAD

$ git fetch origin development                          
From github.privateserver:REPO/ae
 \* branch            development -> FETCH_HEAD

$ gl history -l 10 -c -b origin/development
DEBUG: PREFETCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin

DEBUG: POSTFETCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin

DEBUG: LOOKUP: BRANCH: origin/development 

DEBUG: PRE-REMOTEBRANCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin - GITBRANCH: None

✘ Some internal error occurred
...

$ git fetch origin
warning: no common commits
remote: Enumerating objects: 57, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 97010 (delta 11), reused 22 (delta 2), pack-reused 96953
Receiving objects: 100% (97010/97010), 207.13 MiB | 28.37 MiB/s, done.
Resolving deltas: 100% (62073/62073), done.
From github.privateserver:REPO/ae
 \* [new branch]      BRANCH_1 -> origin/BRANCH_1
...

(ae-env) [1243] (polal02@polal02-L22951) /home/polal02/Dev/ae> gl history -l 10 -c -b origin/development
DEBUG: PREFETCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin

DEBUG: POSTFETCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin

DEBUG: LOOKUP: BRANCH: origin/development 

DEBUG: PRE-REMOTEBRANCH: SELF.NAME: origin - BRANCH: development - SELF.GIT_REMOTE_NAME: origin - GITBRANCH: <_pygit2.Branch object at 0x2b06430>

597f7d9 ...
894886a ...
...
**************
So I have reason to believe that Gitless successfully fetches the remote branch. It is pygit2's `lookup_branch` call that returns None unless you fetch the entire repository via `git fetch repo` (no branch).  

Anything you can add to Gitless will make it better but it does not absolve the pygit2 lookup_branch behavior. Perhaps this is something worth bringing to the attention of the pygit2 dev team.

In any event, I now understand the issue sufficiently to be able to workaround it in a satisfactory manner. Thanks for your support. Keep up the good work.

**Comment by spderosso** [comment]
#215
