### ISSUE TITLE
'gl' command doesn't work in Windows PowerShell due to a conflict with 'Get-Location'

### ISSUE THREAD

**Issue by CrowderSoup** [sdg-mit/gitless#36]
I installed gitless via pip just a few minutes ago and right away noticed something was up as I couldn't use the gl command at all. As it turns out, 'gl' is a global command alias in PowerShell that can't be overwritten. I'm not sure that this is really a fixable issue, unless the command itself is changed, but I just wanted to make others aware of the issue and post my workaround.

**EDIT:** I should be clear that in PowerShell 'gl' is an alias of [Get-Location](https://technet.microsoft.com/en-us/library/ee176853.aspx).

The simple solution to this is to edit your powershell profile and add an alias for gitless. Something other than 'gl'.

```
Set-Alias g c:\python27\scripts\gl.exe
```

I used a simple 'g' as it's nice to only have to type one letter. You can use anything though, and be sure to point the path of the alias to where gitless is actually installed (depends on your system/what version of python you're using).

**Comment by hyochan** [comment]
@CrowderSoup Thanks this is helpful even in 2022 👍
