### ISSUE TITLE
Remote branch isn't created on publish

### ISSUE THREAD

**Issue by skorokithakis** [sdg-mit/gitless#39]
The documentation says that a remote branch will be created if it doesn't exist, but that's not what I'm seeing:

~~~
12:35:11 $ gl publish origin/fix/migrations
# Branch "fix/migrations" doesn't exist in remote "origin"
~~~

**Comment by spderosso** [comment]
Yeah, the documentation is a bit outdated. In the current version there's no way of creating a remote branch but this will be fixed on the next release. 98a2e3649af0aa10583d2ee2ec76ca6de9009130 introduces a new (hopefully more intuitive) way of creating remote branches. 

Thanks for the bug report

**Comment by spderosso** [comment]
https://github.com/sdg-mit/gitless/releases/tag/v0.8
