### ISSUE TITLE
Missing copy of GPL v2

### ISSUE THREAD

**Issue by peterjc** [sdg-mit/gitless#46]
https://github.com/sdg-mit/gitless/blob/master/LICENSE.md says:

> Copyright (C) 2013 Santiago Perez De Rosso
> 
> This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
> 
> This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

As per https://www.gnu.org/licenses/gpl-howto.html you should include a copy of the GPL text, e.g. as the LICENSE file itself?

**Comment by spderosso** [comment]
03c98d0ba2deefa59d5c6aded48ff06c610a59a9
