### ISSUE TITLE
Bringing unstaged changes from master into current branch

### ISSUE THREAD

**Issue by dangom** [sdg-mit/gitless#47]
I switched from master to a branch with `gl switch other-branch`, but forgot to pass the `-mo` flag. Now I am in other-branch with a clean directory. 
Can I bring in the unstaged changes from master into other-branch?
Do I have to switch back and forth and pass the `-mo` flag, or is there an simpler command?

It seems that mixing `gl` and `git` might not be the best idea when branching (for those used to git).

**Comment by spderosso** [comment]
You need to switch back to `master` and then switch to `other-branch` with the `-mo` flag. I'd rather avoid adding a flag (or simpler command) for applying uncommitted changes from a branch onto the current one. It seems unnecessary since switching back and forth is not too bad.
