### ISSUE TITLE
gl commit fails when EDITOR environment variable contains spaces

### ISSUE THREAD

**Issue by sid-kap** [sdg-mit/gitless#64]
I get the following error message when I run `gl commit`:
```
✘ Couldn't launch editor /home/sidharth/bin/my_vim
  ➜ change the value of git's core.editor setting
✘ Missing commit message
```

The same thing doesn't happen when I run `git commit`. 

This information might help: `/home/sidharth/bin/my_vim` is a script that runs Neovim, passing the path to my vimrc file as an argument. It's an executable text file with the contents:
```
/usr/bin/vim -u ~/.vimrc $@
```

Any idea why this is happening?

**Comment by sid-kap** [comment]
Just realized, it's likely that this problem originates in pygit, not in gitless.

**Comment by sid-kap** [comment]
I think I've found the issue. I was trying it in two different ways, both of which don't work:

- The first thing I tried was my fault. I had not added a shebang (`#! /bin/sh`) to the `/home/sidharth/bin/my_vim` file, so python didn't know how to open it. Adding this fixed it.
- Another thing I tried also didn't work. This might be gitless's fault, and could maybe be fixed. In `commit_dialog.py`, gitless calls `subprocess.call([editor, fp])`, where `editor` is the string found from either the `EDITOR` environment variable or from gitconfig's core.editor variable. This works properly when `editor` is a one-word string like "vim", but not when it's a multi-part command like "vim -u ~/.vimrc". Git handles this the way that I want—it does the equivalent of `subprocess.call(["vim", "-u", "~/.vimrc", fp])`, but Gitless does the equivalent of `subprocess.call(["vim -u ~/.vimrc", fp])`, which doesn't work.

Should Gitless handle multi-part editor commands in the same way that Git handles them?

**Comment by DouglasLivingstone** [comment]
I'm unfamiliar with using Neovim as an editor, but is this correct?

    /usr/bin/vim -u ~/.vimrc $@

Perhaps it should be:

    /usr/bin/vim -u ~/.vimrc "$@"

http://stackoverflow.com/questions/4824590/propagate-all-arguments-in-a-bash-shell-script

**Comment by sid-kap** [comment]
Thanks!
