### ISSUE TITLE
Can't publish tag

### ISSUE THREAD

**Issue by chmike** [sdg-mit/gitless#72]
I created a tag on a published commit. But I can't publish the tag with gitless.

The commands equivalent to `git push origin --tags` or `git push origin <tag>` are missing. It should also be possible to define annotated tags.

**Comment by spderosso** [comment]
To create a remote tag you use the `gl tag` command. It works the same way as with branches. From the docs (see [gitless.com](http://gitless.com)):

> 
Uploading Changes. To send changes upstream you use `gl publish`. The publish command will default to updating the upstream branch of the current branch if none is given as input. What if you want to create or delete a remote branch? You can do so with the `gl branch` command. If you do `gl branch -c experiment/develop` this will create a branch develop that lives in the remote experiment (same for delete). To list remote branches use the `r/remote` flag of `gl branch`. Creating or deleting remote tags works the same way as with remote branches. If you do `gl tag -c experiment/v1.0` this will create a new tag v0.1 that lives in the remote experiment. You can also list remote tags with the `r/remote` flag of gl tag.

**Comment by spderosso** [comment]
Created #73  for annotated tags
