### ISSUE TITLE
gitless doesnt understand whitespace in core.editor

### ISSUE THREAD

**Issue by JohanSpaedtke** [sdg-mit/gitless#78]
I'm trying out gitless but found that it doesn't properly handle a core.editor setting with a space in the path.

my .gitconfig file

```
[core]
    editor = "'/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl'" -w  
```

result when running gl commit                                                                                                                                                                     

```
✘ Couldn't launch editor '/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl' -w
  ➜ change the value of git's core.editor setting
```

but when i run git commit it works just fine.

**Comment by spderosso** [comment]
b70bb46d592fb925d7cae0e6ae2ec87ae9fe1025, aba7c5c3df58c59176aa2a9311ec5e7626f1f0c0
