### ISSUE TITLE
How to delete or rename a file ?

### ISSUE THREAD

**Issue by chmike** [sdg-mit/gitless#83]
I I couldn't find an example of how to rename or remove a file. 
This is what I would do intuitively, but I don't know if it's correct:

* To remove a file (git rm) I would first untrack the file and remove it. Is untracking required ? Is that the correct method ?

* To rename or move a file (git mv), I would untrack it, then rename or move it, then track it again.  Is that the correct way ?

If yes, may I suggest to add a few lines to the documentation ? This is not obvious and when it's in the documentation there is no need to guessing about it.

**Comment by chmike** [comment]
Mmh, just tested it. There is no need to previously untrack files when deleting or removing them. 
Simply rm or mv files. Track the renamed or moved file with its new name. That's it. 

A few lines in the documentation showing these operations would be helpful.

**Comment by spderosso** [comment]
bf550dbbcb4947b90ce19e87983d417d474766e0
