### ISSUE TITLE
Support for amend ? 

### ISSUE THREAD

**Issue by chmike** [sdg-mit/gitless#84]
I would like to amend a commit. 

Apparently I should use `gl branch -sh <commit_id>` where `<commit_id>` is the hash of the previous commit.  Are there handy shortcuts to specify *n* step back in commit sequence history ? 
e.g. ` ^1`. 

Again, some documentation on how to amend would be helpful.

**Comment by spderosso** [comment]
Like in Git, you can use `HEAD^n` (or `HEAD~n`, `HEAD@{n}`) to specify the commit that is `n` commits away from head

**Comment by chmike** [comment]
Thank you. I should have tried that. 
Is there a way I could contribute with a Pull Request to the documentation ?

**Comment by spderosso** [comment]
Yes, you can! the website is on the `gh-pages` branch. Here's an example of a pull request fixing documentation:  #66

**Comment by spderosso** [comment]
7e0bed868c8a5f0edc423f463d74a21c3ee4ca18
