### ISSUE TITLE
Version of binaries should be displayed on  http://gitless.com

### ISSUE THREAD

**Issue by chmike** [sdg-mit/gitless#87]
The binaries provided on the http://gitless.com/ web pages are very handy. 
Currently the version of the binaries is not displayed in the http://gitless.com/ web page.
As a consequence we don't know if we may/should update our local binary copy. 

It should also be possible to download older binary versions just in case a bug slips through the latest binary. But that enhancement proposal is less useful.

**Comment by spderosso** [comment]
6351465a31713c71d3a141aec14e6f0b482efe6c
