### ISSUE TITLE
Another internal error occurred

### ISSUE THREAD

**Issue by megadr01d** [sdg-mit/gitless#91]
I was playing with `legit` and it threw me some errors and didn't like it so uninstalled it. After that, I got this error on my test repo, something about someone being beheaded...

```
$ git status
HEAD detached at origin/master
nothing to commit, working tree clean
```

```
$ gl status
✘ Some internal error occurred
  ➜ If you want to help, see http://gitless.com for info on how to report bugs and include the following information:
  
  0.8.4
  
  Traceback (most recent call last):
    File "/usr/local/Cellar/gitless/0.8.4/libexec/lib/python2.7/site-packages/gitless/cli/gl.py", line 73, in main
      return SUCCESS if args.func(args, repo) else ERRORS_FOUND
    File "/usr/local/Cellar/gitless/0.8.4/libexec/lib/python2.7/site-packages/gitless/cli/gl_status.py", line 31, in main
      curr_b = repo.current_branch
    File "/usr/local/Cellar/gitless/0.8.4/libexec/lib/python2.7/site-packages/gitless/core.py", line 199, in current_branch
      b = self.git_repo.lookup_reference('GL_FUSE_ORIG_HEAD').resolve()
  KeyError: 'GL_FUSE_ORIG_HEAD'
```

[EDIT] Fixed it with `git checkout master`, just reporting the error.

**Comment by spderosso** [comment]
If you are using `git` there are states in which you can get your git repo that Gitless won't be able to map to the Gitless world. We should probably report some kind of message instead of crashing though.

**Comment by megadr01d** [comment]
I thought both `git` and `gl` were interchangeable but a standard message for all these unmapped situations such as "Internal error. Please fix it with git before proceeding" would be better than a traceback, I agree.
