### ISSUE TITLE
Combining gl branch option-c and -su should report an error

### ISSUE THREAD

**Issue by chmike** [sdg-mit/gitless#97]
The instruction ` gl branch -c origin/test2 -su origin/test2` doesn't report an error, but only execute the ` gl branch -c origin/test2`. 

It would be handy to be able to create and set the upstream branch in one instruction like for instance `gl branch -csu origin/test2`.

**Comment by chmike** [comment]
Also when I tried `gl branch -c test4 -c origin/test4` only the last `-c origin/test4` was taken in account. 
It should ideally report an error.

**Comment by spderosso** [comment]
255b6d4fd2270429c666bc15598134f106e8f4d7
